Add true and false as PseudoTypes
phpDocumentor/TypeResolver pull request #113
Opened 2020-08-21 10:52 UTC by mvriel

In this change, I have made more allowance for identifying types as
PseudoTypes and to ensure they are identified as both their underlying
and pseudo-type.

Using instanceof, you can identify whether it is the PseudoType, a
pseudotype, but also as the underlying type.

2020-08-22 10:41 UTC, jaapio requested changes

2020-08-22 10:41 UTC, jaapio commented on src/PseudoTypes/False_.php
> +final class False_ extends Boolean implements PseudoType
Moving this class to another namespace isn't possible :-( becaus of BC.

2020-08-22 10:41 UTC, jaapio commented on src/PseudoTypes/True_.php
> +final class True_ extends Boolean implements PseudoType
Moving this class to another namespace isn't possible :-( becaus of BC.

2020-08-24 06:42 UTC, mvriel commented on src/PseudoTypes/False_.php
> +final class False_ extends Boolean implements PseudoType
As discussed on Slack: I'll add a class_alias to the old name. The new namespace helps clarify

2020-08-24 06:43 UTC, mvriel commented on src/PseudoTypes/True_.php
> +final class True_ extends Boolean implements PseudoType
As discussed on Slack: I'll add a class_alias to the old name. The new namespace helps clarify

2020-08-24 06:43 UTC, jaapio commented on src/PseudoTypes/False_.php
> +final class False_ extends Boolean implements PseudoType
It might be good to introduce a deprecation warning on those aliases :-)

2020-08-25 05:52 UTC, mvriel commented
The BC break mentioned in the build is mitigated by using class_alias in the False_ and True_ classes. The tool is apparently unable to detect that and I even added a test to check the BC

2020-08-25 05:53 UTC, mvriel commented on src/PseudoTypes/False_.php
> +final class False_ extends Boolean implements PseudoType
I have been unable to add a deprecation warning; at least: I don't know how I would accomplish that

2020-09-02 21:22 UTC, jaapio approved these changes

2020-09-02 21:29 UTC, merged